### ISSUE TITLE
Panicking instead of returning RocketErr

### ISSUE THREAD

**Issue by tanis2000** [Darksecond/rust-rocket#2]
Is it just me or lines like this one https://github.com/Darksecond/rust-rocket/blob/master/src/client.rs#L92 actually panic instead of throwing back a RocketErr?

**Comment by Darksecond** [comment]
yes, it can probably be replaced with a map_err and a `?`. I would welcome a pull request very much, otherwise I might work on it over the weekend

**Comment by Darksecond** [comment]
It can still be better, but at least it does not panic anymore in `connect`.
